/* Vet INC Enterprise workspace: authenticated Supabase records, no sample data. */
const SB_URL='https://rnqhhzatlxmyvccdvqkr.supabase.co';
const SB_ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJucWhoemF0bHhteXZjY2R2cWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMTQ5ODUsImV4cCI6MjA5MDU5MDk4NX0.zokle21pVEPG5bIOFiyZIWYkYIwhkolWNOhJ7Cbub30';
const $=s=>document.querySelector(s);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={session:null,user:null,orgs:[],org:null,members:[],changes:[],allTasks:[],allLocations:[],change:null,tasks:[],locations:[],priceItems:[],approvals:[],events:[],tab:'Overview',view:'Pricing changes',query:'',message:'',error:false};
function notify(text,error=false){state.message=text;state.error=error;const el=$('#notice');if(el){el.textContent=text;el.className='message'+(error?' error':'');el.hidden=!text}else if(error)alert(text)}
async function api(path,{method='GET',body,auth=true}={}){
 let token=state.session?.access_token;
 if(auth&&state.session&&Date.now()>(state.session.expires_at||0)*1000-45000){await refreshSession();token=state.session?.access_token}
 const res=await fetch(SB_URL+path,{method,headers:{apikey:SB_ANON,...(auth&&token?{Authorization:'Bearer '+token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
 let data;try{data=await res.json()}catch{data=null}
 if(!res.ok)throw Error(data?.msg||data?.error_description||data?.message||data?.error||'Request failed ('+res.status+')');
 return data;
}
async function refreshSession(){const saved=state.session;if(!saved?.refresh_token)throw Error('Your session expired. Please sign in again.');const data=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:saved.refresh_token},auth:false});setSession(data)}
function setSession(s){state.session={...s,expires_at:s.expires_at||Math.floor(Date.now()/1000)+s.expires_in};state.user=s.user||state.user;sessionStorage.setItem('vetinc_enterprise_session',JSON.stringify(state.session))}
function logout(){sessionStorage.removeItem('vetinc_enterprise_session');state.session=null;state.user=null;state.org=null;state.change=null;render()}
async function rpc(name,args){return api('/rest/v1/rpc/'+name,{method:'POST',body:args})}
async function select(table,query){return api('/rest/v1/'+table+'?'+query)}
function notice(){return `<div id="notice" class="message${state.error?' error':''}" ${state.message?'':'hidden'}>${safe(state.message)}</div>`}
function brand(){return `<a class="brand" href="https://vetinc.ca/"><img src="logo.png" alt="Vet INC"><span><strong>Vet INC</strong><small>Enterprise workspace</small></span></a>`}
function render(){if(!state.session){$('#app').innerHTML=`<section class="panel auth">${brand()}<h1>Sign in to enterprise pricing</h1><p>Only members of an organization can see its pricing changes. This workspace does not change clinic prices automatically.</p>${notice()}<form id="login-form"><div class="field"><label for="email">Work email</label><input id="email" type="email" name="email" required autocomplete="username"></div><div class="field"><label for="password">Password</label><input id="password" type="password" name="password" required autocomplete="current-password"></div><button class="btn primary" type="submit">Sign in</button></form><div class="divider"></div><button class="btn" type="button" data-action="magic">Email me a sign-in link instead</button><p class="footnote">An email link can create a new login, but it does not grant access to any existing organization. Your organization admin must add you to their team.</p></section>`;return}
 $('#app').innerHTML=`<div class="layout"><aside class="side">${brand()}<div class="org"><small>ORGANIZATION</small><b>${safe(state.org?.name||'No organization selected')}</b>${state.orgs.length>1?`<select id="org-switch" aria-label="Select organization" style="margin-top:7px;width:100%;background:#1d364e;color:white;border:1px solid #69839c;border-radius:4px;font-size:10px;padding:5px">${state.orgs.map(o=>`<option value="${safe(o.id)}" ${o.id===state.org?.id?'selected':''}>${safe(o.name)}</option>`).join('')}</select>`:''}</div><label>WORKSPACE</label><nav aria-label="Workspace views">${['Pricing changes','Open team work','Approvals','Locations','Change record'].map(v=>`<button type="button" data-view="${safe(v)}" class="${v===state.view?'active':''}">${safe(v)}</button>`).join('')}</nav><footer>${safe(state.user?.email||'Signed in')}<br><button type="button" class="link" style="color:#a9c6e5" data-action="logout">Sign out</button></footer></aside><div class="content"><header class="bar"><span>Price operations / <b>${safe(state.view)}</b></span><span>${safe(state.org?.name||'Organization setup')}</span></header><main class="main">${notice()}${state.org?renderWorkspace():renderOnboarding()}</main></div></div>`}
function renderOnboarding(){return `<div class="head"><div><div class="eyebrow">Getting started</div><h1>Set up your organization</h1><p>No enterprise organization is linked to your login yet.</p></div></div><section class="panel empty"><h2>Create a private workspace</h2><p>Only you will have access initially. Add colleagues after setup. No example changes or clinic data will be created.</p><button class="btn primary" type="button" data-action="new-org">Create organization</button></section>`}
function status(s){return `<span class="status ${safe(s)}">${safe(({draft:'Draft',review:'Awaiting approval',approved:'Approved',rollout:'In rollout',confirmed:'Confirmed'})[s]||s)}</span>`}
function initials(id){const m=state.members.find(x=>x.user_id===id);return m?.member_email||'Team member'}
function renderWorkspace(){let c=state.change;if(c)return renderDetail(c);const changes=state.changes.filter(x=>{const q=state.query.toLowerCase();const inView=state.view==='Pricing changes'||(state.view==='Open team work'&&state.allTasks.some(t=>t.change_id===x.id&&t.status==='open'))||(state.view==='Approvals'&&x.status==='review')||(state.view==='Locations'&&x.status==='rollout')||(state.view==='Change record'&&x.status==='confirmed');return inView&&(!q||[x.title,x.description,x.status,initials(x.owner_id)].some(a=>String(a||'').toLowerCase().includes(q)))});return `<div class="head"><div><div class="eyebrow">Enterprise price operations</div><h1>${safe(state.view)}</h1><p>Coordinate pricing decisions, team work, approvals and implementation across your organization.</p></div><div class="inline-actions">${state.members.find(x=>x.user_id===state.user?.id)?.role==='admin'?'<button type="button" class="btn" data-action="add-member">Add team member</button>':''}${can('admin','pricing')?'<button type="button" class="btn primary" data-action="new-change">+ New pricing change</button>':''}</div></div><section class="panel"><div class="panel-h"><div><h2>${safe(state.view)}</h2><p>${state.view==='Pricing changes'?'Your organization’s actual change records.': 'Open a change to see its work, approvals, locations and history.'}</p></div><input class="search" id="search" type="search" aria-label="Search pricing changes" placeholder="Search changes" value="${safe(state.query)}"></div>${changes.length?`<div class="tablewrap"><table><thead><tr><th>CHANGE</th><th>OWNER</th><th>STAGE</th><th>TARGET DATE</th><th></th></tr></thead><tbody>${changes.map(x=>`<tr><td><strong>${safe(x.title)}</strong><small>${safe(x.description||'No description yet')}</small></td><td>${safe(initials(x.owner_id))}</td><td>${status(x.status)}</td><td>${safe(x.effective_date||'Not set')}</td><td><button type="button" class="link" data-open="${safe(x.id)}">Open →</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><h2>${state.query?'No matching changes':'No pricing changes yet'}</h2><p>${state.query?'Try another search.':'Create your first company-wide change to assign work, collect approval and track location progress. Nothing is added automatically.'}</p>${!state.query?'<button type="button" class="btn primary" data-action="new-change">Create first change</button>':''}</div>`}</section>`}
function can(...roles){return roles.includes(state.members.find(m=>m.user_id===state.user?.id)?.role)}
function renderDetail(c){let open=state.tasks.filter(t=>t.status==='open').length,confirmed=state.locations.filter(l=>l.state==='confirmed').length;const next={draft:['Submit for approval','submit',['admin','pricing']],review:['Approve','approve',['admin','finance']],approved:['Begin rollout','start',['admin','operations']],rollout:['Confirm change','confirm',['admin','operations']]}[c.status];return `<button class="link" type="button" data-action="back">← All changes</button><div class="detail-head"><div><div class="eyebrow">Pricing change · ${safe(c.id.slice(0,8))}</div><h1>${safe(c.title)}</h1><p>${safe(c.description||'No description provided.')}</p></div><div class="inline-actions">${status(c.status)}${next&&can(...next[2])&&!(next[1]==='approve'&&c.owner_id===state.user?.id)?`<button type="button" class="btn primary" data-transition="${next[1]}">${next[0]}</button>`:''}${c.status==='review'&&can('admin','finance')?'<button class="btn" type="button" data-transition="return">Return for changes</button>':''}</div></div><div class="stats"><div class="stat"><small>Owner</small><b>${safe(initials(c.owner_id))}</b></div><div class="stat"><small>Proposed price lines</small><b>${state.priceItems.length}</b></div><div class="stat"><small>Open team work</small><b>${open}</b></div><div class="stat"><small>Locations confirmed</small><b>${confirmed} / ${state.locations.length}</b></div></div><section class="panel"><nav class="tabs" aria-label="Change workspace">${['Overview','Proposed prices','Team work','Approvals','Locations','Record'].map(t=>`<button type="button" data-tab="${t}" class="${state.tab===t?'active':''}">${t}</button>`).join('')}</nav><div class="section">${renderTab(c)}</div></section><p class="footnote">This workspace records coordination and manual confirmations. It does not connect to a practice system or change prices automatically.</p>`}
function renderTab(c){if(state.tab==='Overview')return `<h2>Change overview</h2><p>The agreed scope and team decisions stay attached to this change.</p><div class="item"><div><strong>Current stage</strong><small>Only authorized team roles can move a change forward.</small></div>${status(c.status)}</div><div class="item"><div><strong>Locations in scope</strong><small>Add locations before approval. A location's confirmation is a recorded action, not a PMS write.</small></div><strong>${state.locations.length}</strong></div><div class="item"><div><strong>Open work</strong><small>Review outstanding items before sign-off.</small></div><strong>${state.tasks.filter(t=>t.status==='open').length}</strong></div>`;
if(state.tab==='Proposed prices')return `<div class="panel-h" style="padding:0 0 15px"><div><h2>Proposed service prices</h2><p>These are proposals for approval. Nothing here updates a clinic’s practice system.</p></div>${can('admin','pricing')&&c.status==='draft'?'<button class="btn primary" type="button" data-action="new-price">+ Add price</button>':''}</div>${state.priceItems.length?`<div class="tablewrap"><table><thead><tr><th>SERVICE</th><th>CODE</th><th>CURRENT</th><th>PROPOSED</th><th>NOTE</th></tr></thead><tbody>${state.priceItems.map(i=>`<tr><td><strong>${safe(i.service_name)}</strong></td><td>${safe(i.service_code||'—')}</td><td>${safe(i.currency)} ${safe(Number(i.current_price).toFixed(2))}</td><td><strong>${safe(i.currency)} ${safe(Number(i.proposed_price).toFixed(2))}</strong></td><td>${safe(i.note||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h2>No proposed prices yet</h2><p>Add the actual services and amounts before submitting this change for approval.</p></div>'}`;
if(state.tab==='Team work')return `<div class="panel-h" style="padding:0 0 15px"><div><h2>Team work</h2><p>Assign the decisions and preparation work needed for this change.</p></div>${can('admin','pricing','operations')&&c.status!=='confirmed'?'<button class="btn primary" type="button" data-action="new-task">+ Add work</button>':''}</div>${state.tasks.length?state.tasks.map(t=>`<div class="item"><div><strong>${safe(t.title)}</strong><small>${safe(initials(t.assigned_to))} · ${safe(t.status)}</small></div>${t.status==='open'&&(can('admin','pricing','operations')||t.assigned_to===state.user?.id)?`<button class="btn" type="button" data-finish="${safe(t.id)}">Mark complete</button>`:''}</div>`).join(''):'<div class="empty"><h2>No work assigned</h2><p>Add a real team item when one needs to be resolved.</p></div>'}`;
if(state.tab==='Approvals')return `<h2>Approval record</h2><p>Approval is recorded against this change when an authorized approver acts. Open work must be resolved first.</p>${state.approvals.length?state.approvals.map(a=>`<div class="item"><div><strong>${safe(a.decision)}</strong><small>${safe(initials(a.actor_id))} · ${safe(new Date(a.created_at).toLocaleString())}</small></div><span>${safe(a.note||'')}</span></div>`).join(''):'<div class="empty"><h2>No approvals recorded</h2><p>This change has not been approved in this workspace.</p></div>'}`;
if(state.tab==='Locations')return `<div class="panel-h" style="padding:0 0 15px"><div><h2>Location progress</h2><p>Location records are added by your team, not imported from an example dataset.</p></div>${can('admin','pricing','operations')&&c.status==='draft'?'<button class="btn primary" type="button" data-action="new-location">+ Add location</button>':''}</div>${state.locations.length?state.locations.map(l=>`<div class="item"><div><strong>${safe(l.name)}</strong><small>${safe(l.state==='confirmed'?'Manually confirmed on '+new Date(l.confirmed_at).toLocaleString():l.state)}</small></div><div class="right">${l.state==='confirmed'?status('confirmed'):can('admin','operations')&&c.status!=='confirmed'?`<button class="btn" type="button" data-location="${safe(l.id)}">Update status</button>`:''}</div></div>`).join(''):'<div class="empty"><h2>No locations in scope</h2><p>Add actual organization locations before rollout. A change cannot be confirmed until each included location is confirmed.</p></div>'}`;
return `<h2>Change record</h2><p>A time-ordered record of actions taken in this workspace. No simulated events are shown.</p>${state.events.length?state.events.map(e=>`<div class="item"><div><strong>${safe(e.action)}</strong><small>${safe(initials(e.actor_id))} · ${safe(new Date(e.created_at).toLocaleString())}</small></div><span>${safe(e.detail)}</span></div>`).join(''):'<div class="empty"><h2>No activity yet</h2><p>Actions taken in this workspace will appear here.</p></div>'}`}
async function load(){state.orgs=await select('enterprise_orgs','select=id,name,created_at&order=created_at.desc');state.org=state.orgs.find(o=>o.id===state.org?.id)||state.orgs[0]||null;if(state.org){const id=encodeURIComponent(state.org.id);let [members,changes,allTasks]=await Promise.all([select('enterprise_members',`select=user_id,member_email,role&org_id=eq.${id}`),select('enterprise_changes',`select=*&org_id=eq.${id}&order=created_at.desc`),select('enterprise_tasks',`select=change_id,status,assigned_to&org_id=eq.${id}&status=eq.open`)]);state.members=members;state.changes=changes;state.allTasks=allTasks;if(state.change){state.change=changes.find(c=>c.id===state.change.id)||null;if(state.change)await loadDetail()}}else{state.members=[];state.changes=[];state.change=null}render()}
async function loadDetail(){const id=encodeURIComponent(state.change.id);[state.tasks,state.locations,state.priceItems,state.approvals,state.events]=await Promise.all([select('enterprise_tasks',`select=*&change_id=eq.${id}&order=created_at.desc`),select('enterprise_locations',`select=*&change_id=eq.${id}&order=name.asc`),select('enterprise_price_items',`select=*&change_id=eq.${id}&order=created_at.asc`),select('enterprise_approvals',`select=*&change_id=eq.${id}&order=created_at.desc`),select('enterprise_events',`select=*&change_id=eq.${id}&order=created_at.desc`)]);render()}
function modal(title,description,fields,submit){$('#modal-title').textContent=title;$('#modal-description').textContent=description;$('#modal-form').innerHTML=fields+`<div class="modal-actions"><button class="btn" type="button" data-action="cancel">Cancel</button><button class="btn primary" type="submit">${safe(submit)}</button></div>`;$('#modal-form').dataset.kind=title;$('#modal-back').classList.remove('hidden');$('#modal-form').querySelector('input,select,textarea')?.focus()}
function closeModal(){$('#modal-back').classList.add('hidden');$('#modal-form').innerHTML=''}
const field=(name,label,type='text',required=true)=>`<div class="field"><label for="m-${name}">${label}</label><input id="m-${name}" name="${name}" type="${type}" ${type==='number'?'min="0" step="0.01"':''} ${required?'required':''}></div>`;
function actions(a){if(a==='logout'){logout();return}if(a==='back'){state.change=null;state.tab='Overview';render();return}if(a==='cancel'){closeModal();return}if(a==='magic'){let email=$('#email')?.value?.trim();if(!email){notify('Enter your work email first.',true);$('#email')?.focus();return}api('/auth/v1/otp',{method:'POST',body:{email,create_user:true,options:{email_redirect_to:location.origin+location.pathname}},auth:false}).then(()=>notify('If this email has an account, check your inbox for a sign-in link.')).catch(e=>notify(e.message,true));return}if(a==='new-org')modal('Create organization','This private workspace will start empty. You can add your team after setup.',field('name','Organization name'),'Create');if(a==='new-change')modal('New pricing change','Describe an actual pricing change; no sample records will be inserted.',field('title','Change name')+`<div class="field"><label for="m-description">Purpose / scope</label><textarea id="m-description" name="description"></textarea></div>`+field('date','Target date','date',false),'Create change');if(a==='add-member')modal('Add team member','This person must already have a Vet INC login. Only organization admins can add team members.',field('email','Team member email','email')+`<div class="field"><label for="m-role">Role</label><select id="m-role" name="role"><option value="pricing">Pricing</option><option value="finance">Finance</option><option value="operations">Operations</option><option value="viewer">Viewer</option></select></div>`,'Add member');if(a==='new-task')modal('Add team work','Give an existing organization member a clear next action.',field('title','Work item')+`<div class="field"><label for="m-assignee">Assign to</label><select id="m-assignee" name="assignee"><option value="">Unassigned</option>${state.members.map(m=>`<option value="${safe(m.user_id)}">${safe(m.member_email)} (${safe(m.role)})</option>`).join('')}</select></div>`,'Add work');if(a==='new-price')modal('Add proposed price','Enter the real service and amounts. Proposed prices are locked when the change is submitted.',field('name','Service name')+field('code','Service code','text',false)+`<div class="grid2">${field('current','Current price','number')}${field('proposed','Proposed price','number')}</div><div class="field"><label for="m-currency">Currency</label><select id="m-currency" name="currency"><option value="CAD">CAD</option><option value="USD">USD</option></select></div>`+field('note','Reason / note','text',false),'Add price');if(a==='new-location')modal('Add location','Use the real location name. Adding it records scope; it does not update that clinic’s pricing.',field('name','Location name'),'Add location')}
async function submitModal(e){e.preventDefault();const form=e.currentTarget,kind=form.dataset.kind,v=Object.fromEntries(new FormData(form));const btn=form.querySelector('[type=submit]');btn.disabled=true;try{if(kind==='Create organization'){await rpc('enterprise_create_org',{p_name:v.name});await load()}if(kind==='New pricing change'){await rpc('enterprise_create_change',{p_org:state.org.id,p_title:v.title,p_description:v.description||'',p_date:v.date||null});await load()}if(kind==='Add team member'){await rpc('enterprise_add_member',{p_org:state.org.id,p_email:v.email,p_role:v.role});await load()}if(kind==='Add team work'){await rpc('enterprise_add_task',{p_change:state.change.id,p_title:v.title,p_assigned_to:v.assignee||null});await load()}if(kind==='Add proposed price'){await rpc('enterprise_add_price_item',{p_change:state.change.id,p_name:v.name,p_code:v.code||'',p_current:Number(v.current),p_proposed:Number(v.proposed),p_currency:v.currency,p_note:v.note||''});await load()}if(kind==='Add location'){await rpc('enterprise_add_location',{p_change:state.change.id,p_name:v.name});await load()}closeModal();notify('Saved to your organization workspace.')}catch(err){btn.disabled=false;notify(err.message,true)}}
async function doTransition(action){const explain={submit:'Send this change for authorized review?',approve:'Approve this change and record your sign-off?',return:'Return this change to draft for revision?',start:'Begin coordinating the approved rollout? This does not change prices.',confirm:'Record this change as complete? All included locations must be confirmed first.'};if(!confirm(explain[action]))return;try{await rpc('enterprise_transition',{p_change:state.change.id,p_action:action,p_note:''});await load();notify('Change stage recorded.')}catch(e){notify(e.message,true)}}
async function changeLocation(id){const l=state.locations.find(x=>x.id===id);if(!l)return;const answer=prompt('Set location status: ready, held, or confirmed\nConfirmation records a manual completion. It does not update the clinic system.',l.state);if(answer===null)return;const value=answer.trim().toLowerCase();if(!['ready','held','confirmed'].includes(value)){notify('Choose ready, held, or confirmed.',true);return}if(value==='confirmed'&&!confirm('Confirm that an authorized person completed and checked the pricing change at '+l.name+'? This records a manual confirmation; it does not write to the clinic system.'))return;try{await rpc('enterprise_set_location',{p_location:id,p_state:value,p_method:value==='confirmed'?'manual':null});await load();notify('Location status recorded.')}catch(e){notify(e.message,true)}}
$('#app').addEventListener('submit',async e=>{if(e.target.id!=='login-form')return;e.preventDefault();const f=new FormData(e.target);try{const data=await api('/auth/v1/token?grant_type=password',{method:'POST',body:{email:f.get('email'),password:f.get('password')},auth:false});setSession(data);state.message='';await load()}catch(err){notify(err.message,true)}});
$('#app').addEventListener('click',async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.action){actions(b.dataset.action);return}if(b.dataset.view){state.view=b.dataset.view;state.change=null;state.query='';render();return}if(b.dataset.open){state.change=state.changes.find(c=>c.id===b.dataset.open);state.tab='Overview';await loadDetail();return}if(b.dataset.tab){state.tab=b.dataset.tab;render();return}if(b.dataset.transition){await doTransition(b.dataset.transition);return}if(b.dataset.location){await changeLocation(b.dataset.location);return}if(b.dataset.finish){if(!confirm('Mark this work item complete?'))return;try{await rpc('enterprise_finish_task',{p_task:b.dataset.finish});await load();notify('Work completion recorded.')}catch(err){notify(err.message,true)}}});
$('#app').addEventListener('change',async e=>{if(e.target.id==='org-switch'){state.org=state.orgs.find(o=>o.id===e.target.value)||state.org;state.change=null;state.view='Pricing changes';state.query='';try{await load()}catch(err){notify(err.message,true)}}});
$('#app').addEventListener('input',e=>{if(e.target.id==='search'){state.query=e.target.value;const start=e.target.selectionStart;render();let input=$('#search');input?.focus();input?.setSelectionRange(start,start)}});
$('#modal-form').addEventListener('submit',submitModal);$('#modal-back').addEventListener('click',e=>{if(e.target.id==='modal-back'||e.target.dataset.action==='cancel')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal-back').classList.contains('hidden'))closeModal()});
(async()=>{try{const hash=new URLSearchParams(location.hash.slice(1));if(hash.get('access_token')){setSession({access_token:hash.get('access_token'),refresh_token:hash.get('refresh_token'),token_type:'bearer',expires_in:Number(hash.get('expires_in')||3600)});history.replaceState({},'',location.pathname+location.search)}else if(sessionStorage.getItem('vetinc_enterprise_session'))state.session=JSON.parse(sessionStorage.getItem('vetinc_enterprise_session'));if(state.session){if(Date.now()>state.session.expires_at*1000-45000)await refreshSession();state.user=await api('/auth/v1/user');await load()}else render()}catch(e){logout();notify('Sign in again: '+e.message,true)}})();
